name: CI

on:
  push:
    
  pull_request:
    

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

    - name: Install dependecies, build
      run: |
        make install
        make build

    - name: Run linter
      run: make lint

    - name: Run tests
      run: make test

